name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2.0.1
        with:
          card: stats
          options: username=exwxsz&show_icons=true&include_all_commits=true&theme=buefy
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2.0.1
        with:
          card: top-langs
          options: username=exwxsz&layout=compact&theme=buefy
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github stats"
